Repository Elkokonut/AR-music, pull requests merged in 2022-05, with the labels that each got.

#37 [ADD] loading screen
  index.html
  loading.scss
  package.json
  src/AI/holistic.ts
  src/app.ts
  src/ui.ts
  yarn.lock
Labels: enhancement, M

#39 enhance scaling + object alignment
  css/loading.scss
  css/scene.css
  index.html
  src/AR/objects/Instruments/Drum.ts
  src/AR/objects/Instruments/Drumstick.ts
  src/AR/objects/Instruments/InstrumentFactory.ts
  src/AR/objects/Instruments/Microphone.ts
  src/AR/objects/Object3D.ts
  src/AR/objects/Occlusers/Occluser.ts
  src/AR/objects/Occlusers/Palm.ts
  src/AR/objects/Occlusers/Phalanx.ts
  src/AR/objects/Trackers/BodyTrackerObject.ts
  src/AR/scenes/BodyTrackerScene.ts
  src/AR/scenes/Scene.ts
  src/Geometry/Distance.ts
  src/Geometry/Hand.ts
  src/Geometry/Keypoint.ts
  src/app.ts
  src/app/app.ts
  src/app/ui.ts
  src/main.ts
  src/test/line-test.ts
  src/test/model_visualization.ts
  src/tools/Distance.ts
  src/tools/keypoints_helper.ts
  static/json/keypoints.json
Labels: AR, L

#43 [ADD] interface v1, albe to change instrument
  css/scene.css
  index.html
  package.json
  src/AR/objects/Instruments/Drumstick.ts
  src/AR/objects/Instruments/InstrumentFactory.ts
  src/AR/objects/Instruments/Microphone.ts
  src/AR/objects/Interface/Button.ts
  src/AR/objects/Interface/Frame.ts
  src/AR/objects/Interface/FrameFactory.ts
  src/AR/objects/Interface/Interface.ts
  src/AR/objects/Interface/Toogle.ts
  src/AR/scenes/BodyTrackerScene.ts
  src/AR/scenes/Scene.ts
  src/AR/utils/ImageTexture.ts
  src/Geometry/Hand.ts
  src/Geometry/Keypoint.ts
  src/app/app.ts
  src/app/ui.ts
  src/main.ts
  static/fonts/gothic-msdf.json
  static/fonts/gothic.png
  yarn.lock
Labels: AR

#59 Drums improvements
  src/AR/objects/Instruments/Drum.ts
  src/AR/objects/Instruments/Drumstick.ts
  src/AR/objects/Instruments/InstrumentFactory.ts
  src/AR/scenes/BodyTrackerScene.ts
  src/tools/OneEuroFilter.ts
  static/models/cymbal/Cymbal.mtl
  static/models/cymbal/Cymbal.obj
  static/models/cymbal/softbox.png
  static/models/cymbal/zildjian-i-family-18-crash-ride.jpeg
  static/models/drumstick/drumstick.fbx
  static/models/red_drum/red_drum.3DS
  static/sound sample/cymbal.wav
  static/sound sample/drum.wav
  static/sound sample/drum_left.wav
  static/sound sample/drum_right.wav
Labels: enhancement, AR

#63 Interface 2d v2
  .parcelrc
  css/loading.scss
  css/model_loading.scss
  index.html
  package.json
  src/AI/Classifier.ts
  src/AI/PoseDetector.ts
  src/AR/objects/Instruments/InstrumentFactory.ts
  src/AR/objects/Interface/Button.ts
  src/AR/objects/Interface/Frame.ts
  src/AR/objects/Interface/FrameFactory.ts
  src/AR/objects/Interface/Interface.ts
  src/AR/objects/Interface/Toogle.ts
  src/AR/objects/Occlusers/Palm.ts
  src/AR/objects/Occlusers/Phalanx.ts
  src/AR/objects/Trackers/Cube.ts
  src/AR/objects/Trackers/Disk.ts
  src/AR/scenes/BodyTrackerScene.ts
  src/AR/scenes/Scene.ts
  src/AR/utils/ImageTexture.ts
  src/Geometry/Hand.ts
  src/Geometry/Keypoint.ts
  src/app/App.ts
  src/app/Ui.ts
  src/main.ts
  src/tools/SoundManager.ts
  static/sound sample/harp.wav
  yarn.lock
Labels: enhancement, AR
