Repository Elkokonut/AR-music, pull requests merged in 2022-04, with the labels that each got.

#19 Typescript
  .eslintignore
  .eslintrc
  .eslintrc.yml
  .github/workflows/lint.yaml
  .gitignore
  index.html
  package.json
  ressources/keypoints.json
  src/AI/holistic.ts
  src/AR/objects/BodyTrackerObject.ts
  src/AR/objects/Cube.ts
  src/AR/objects/Disk.ts
  src/AR/objects/Object3D.js
  src/AR/objects/Object3D.ts
  src/AR/scenes/BodyTrackerScene.ts
  src/AR/scenes/Scene.ts
  src/app.ts
  src/tools/Distance.ts
  src/tools/Keypoint.ts
  src/tools/keypoints_helper.ts
  src/tools/oneEuroFilter.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#23 3 d instrument
  .parcelrc
  index.html
  model_visualization.html
  package.json
  src/AI/holistic.ts
  src/AR/objects/BodyTrackerObject.ts
  src/AR/objects/Cube.ts
  src/AR/objects/Disk.ts
  src/AR/objects/InstrumentFactory.ts
  src/AR/objects/Microphone.ts
  src/AR/objects/Object3D.ts
  src/AR/scenes/BodyTrackerScene.ts
  src/AR/scenes/Scene.ts
  src/app.ts
  src/model_visualization.ts
  src/tools/Distance.ts
  src/tools/Keypoint.ts
  static/json/keypoints.json
  static/models/mic/microphone.fbx
  static/models/mic/textures/Microphone_FBX_Microphone_BaseColor.png
  static/models/mic/textures/Microphone_FBX_Microphone_Height.png
  static/models/mic/textures/Microphone_FBX_Microphone_Metalness.png
  static/models/mic/textures/Microphone_FBX_Microphone_Normal.png
  static/models/mic/textures/Microphone_FBX_Microphone_Roughness.png
  yarn.lock
Labels: enhancement, AR, XL

#26 [ADD] added reverb on mic to mouth
  package.json
  src/AR/objects/Microphone.ts
  src/AR/scenes/BodyTrackerScene.ts
  src/app.ts
  src/tools/Keypoint.ts
  yarn.lock
Labels: enhancement, M

#33 Resize three js
  index.html
  src/AI/holistic.ts
  src/AR/objects/Palm.ts
  src/AR/scenes/BodyTrackerScene.ts
  src/AR/scenes/Scene.ts
  src/app.ts
Labels: bug, AR
